name: strukly

services:
  postgres:
    image: postgres:18-alpine
    container_name: strukly-postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  strukly:
    build:
      context: ./strukly-backend
    container_name: strukly-backend
    # restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - postgres
